const animals = [
  {
    name: "Elephant",
    type: "ESTJ",
    image: "/images/elephant.png",
    description: "Elephants are practical and efficient individuals with a strong sense of responsibility and a desire for order and stability. They are reliable, detail-oriented, and excel in roles that require organization and planning. They value efficiency, structure, and attention to detail. Elephants dislike disorder, inefficiency, and disregard for rules.",
    bestMatch: ["ISTP", "ISFP", "INTP"],
    worstMatch: ["ENFP", "INFP", "ENFJ"],
    thingsTheyLike: "Efficiency, order, practicality",
    thingsTheyHate: "Disorder, inefficiency, lack of structure",
  },
  {
    name: "Lion",
    type: "ENTJ",
    image: "/images/lion.png",
    description: "Lions are confident and ambitious individuals with a strong desire to lead and make a difference in the world. They are strategic and decisive thinkers, often drawn to leadership roles that allow them to use their visionary ideas to guide others. They value challenges, achievement, and making an impact. Lions dislike inefficiency, indecisiveness, and lack of ambition.",
    bestMatch: ["INFJ", "INTJ", "ENFJ"],
    worstMatch: ["ISFP", "ISTP", "ESFP"],
    thingsTheyLike: "Challenges, achievement, making an impact",
    thingsTheyHate: "Inefficiency, indecisiveness, lack of ambition",
  },
  {
    name: "Dolphin",
    type: "ESFJ",
    image: "/images/dolphin.png",
    description: "Dolphins are friendly and outgoing individuals with a strong desire to help others. They are empathetic, caring, and value harmonious relationships. They excel in roles that require strong communication skills and collaboration. Dolphins value harmony, helping others, and socializing. They dislike conflict, criticism, and feeling unappreciated.",
    bestMatch: ["ISTP", "ISFP", "ESFP"],
    worstMatch: ["INTP", "INTJ", "INFJ"],
    thingsTheyLike: "Harmony, helping others, socializing",
    thingsTheyHate: "Conflict, criticism, feeling unappreciated",
  },
  {
    name: "Giraffe",
    type: "ENFJ",
    image: "/images/giraffe.png",
    description: "Giraffes are compassionate and caring individuals with a strong desire to help others and make a positive impact. They are outgoing, sociable, and excel in roles that involve guiding and inspiring others. Giraffes value helping others, cooperation, and personal growth. They dislike conflict, insincerity, and selfishness.",
    bestMatch: ["ISFP", "ISTP", "ESFP"],
    worstMatch: ["INTP", "INTJ", "INFJ"],
    thingsTheyLike: "Helping others, cooperation, personal growth",
    thingsTheyHate: "Conflict, insincerity, selfishness",
  },
  {
    name: "Kangaroo",
    type: "ISTJ",
    image: "/images/kangaroo.png",
    description: "Kangaroos are practical and responsible individuals with a strong desire for order and structure. They are reliable, detail-oriented, and excel in roles that require organization and attention to detail. Kangaroos value organization, structure, and attention to detail. They dislike disorder, unpredictability, and lack of planning.",
    bestMatch: ["ENFP", "ENTP", "ENFJ"],
    worstMatch: ["INFP", "ISFP", "INTP"],
    thingsTheyLike: "Organization, structure, attention to detail",
    thingsTheyHate: "Disorder, unpredictability, lack of planning",
  },
  {
    name: "Penguin",
    type: "ISFJ",
    image: "/images/penguin.png",
    description: "Penguins are practical and dependable individuals with a strong sense of duty and a desire to help others. They are loyal, hardworking, and excel in roles that require reliability and attention to detail. Penguins value helping others, stability, and traditions. They dislike conflict, unpredictability, and disregard for rules.",
    bestMatch: ["ESTP", "ESFP", "ENFP"],
    worstMatch: ["INTP", "INTJ", "INFJ"],
    thingsTheyLike: "Helping others, stability, traditions",
    thingsTheyHate: "Conflict, unpredictability, disregard for rules",
  },
  {
    name: "Owl",
    type: "INTJ",
    image: "/images/owl.png",
    description: "Owls are analytical and strategic individuals with a strong desire to understand the world and solve complex problems. They are independent thinkers and excel in roles that require innovative and critical thinking. Owls value intellectual challenges, independent thinking, and efficiency. They dislike inefficiency, ignorance, and micromanagement.",
    bestMatch: ["ENFP", "ENFJ", "ENTP"],
    worstMatch: ["ESFP", "ESTP", "ISFP"],
    thingsTheyLike: "Intellectual challenges, independent thinking, efficiency",
    thingsTheyHate: "Inefficiency, ignorance, micromanagement",
  },
  {
    name: "Dove",
    type: "INFJ",
    image: "/images/dove.png",
    description: "Doves are insightful and empathetic individuals with a strong desire to understand the deeper meaning of life. They are idealistic, compassionate, and excel in roles that involve helping others and making a positive impact. Doves value meaningful connections, personal growth, and making a difference. They dislike conflict, superficiality, and injustice.",
    bestMatch: ["ENFP", "ENFJ", "ENTP"],
    worstMatch: ["ESFP", "ESTP", "ISFP"],
    thingsTheyLike: "Meaningful connections, personal growth, making a difference",
    thingsTheyHate: "Conflict, superficiality, injustice",
  },
  {
    name: "Cheetah",
    type: "ESTP",
    image: "/images/cheetah.png",
    description: "Cheetahs are adventurous and energetic individuals with a strong desire to experience life to the fullest. They are outgoing, sociable, and excel in roles that involve action and practical skills. Cheetahs value excitement, action, and socializing. They dislike boredom, routine, and being controlled.",
    bestMatch: ["ISFJ", "ESFP", "ESFJ"],
    worstMatch: ["INTJ", "INFJ", "INTP"],
    thingsTheyLike: "Excitement, action, socializing",
    thingsTheyHate: "Boredom, routine, being controlled",
  },
  {
    name: "Peacock",
    type: "ESFP",
    image: "/images/peacock.png",
    description: "Peacocks are fun-loving and spontaneous individuals with a strong desire to enjoy life and make others happy. They are sociable, outgoing, and excel in roles that involve creativity and interpersonal skills. Peacocks value adventures, socializing, and creativity. They dislike negativity, rigid rules, and feeling restricted.",
    bestMatch: ["INTJ", "ISTJ", "ESTJ"],
    worstMatch: ["ISTP", "ISFP", "INTP"],
    thingsTheyLike: "Adventures, socializing, creativity",
    thingsTheyHate: "Negativity, rigid rules, feeling restricted",
  },
  {
    name: "Fox",
    type: "ENTP",
    image: "/images/fox.png",
    description: "Foxes are curious and innovative individuals with a strong desire to explore new ideas and possibilities. They are outgoing, sociable, and excel in roles that involve creative problem-solving and intellectual challenges. Foxes value intellectual challenges, new experiences, and brainstorming. They dislike routine, narrow-mindedness, and excessive rules.",
    bestMatch: ["ISFJ", "ISTJ", "ESTJ"],
    worstMatch: ["ISTP", "ISFP", "INTP"],
    thingsTheyLike: "Intellectual challenges, new experiences, brainstorming",
    thingsTheyHate: "Routine, narrow-mindedness, excessive rules",
  },
  {
    name: "Deer",
    type: "ENFP",
    image: "/images/deer.png",
    description: "Deers are friendly and adaptable individuals with a strong desire to connect with others and make a positive difference in the world. They are creative, imaginative, and excel in roles that involve personal expression and helping others. Deers value meaningful connections, creativity, and personal growth. They dislike conflict, feeling restricted, and insincerity.",
    bestMatch: ["ISTJ", "ISFJ", "ESFJ"],
    worstMatch: ["ISFP", "ISTP", "ESFP"],
    thingsTheyLike: "Meaningful connections, creativity, personal growth",
    thingsTheyHate: "Conflict, feeling restricted, insincerity",
  },
  {
    name: "Sloth",
    type: "ISTP",
    image: "/images/sloth.png",
    description: "Sloths are independent and analytical individuals with a strong desire to understand how things work. They are logical, adaptable, and excel in roles that require problem-solving and hands-on skills. Sloths value intellectual challenges, learning, and autonomy. They dislike rigid structures, ignorance, and being micromanaged.",
    bestMatch: ["ENFJ", "ENFP", "ENTP"],
    worstMatch: ["ESFP", "ESTP", "ISFP"],
    thingsTheyLike: "Intellectual challenges, learning, autonomy",
    thingsTheyHate: "Rigid structures, ignorance, being micromanaged",
  },
  {
    name: "Swan",
    type: "ISFP",
    image: "/images/swan.png",
    description: "Swans are sensitive and artistic individuals with a strong desire for personal freedom and expression. They are compassionate, gentle, and excel in roles that involve creativity and helping others. Swans value creativity, personal values, and making a difference. They dislike conflict, criticism, and feeling unappreciated.",
    bestMatch: ["ESTJ", "ESFJ", "ENFJ"],
    worstMatch: ["INTJ", "INFJ", "INTP"],
    thingsTheyLike: "Creativity, personal values, making a difference",
    thingsTheyHate: "Conflict, criticism, feeling unappreciated",
  },
  {
    name: "Raven",
    type: "INTP",
    image: "/images/raven.png",
    description: "Ravens are logical and innovative individuals with a strong desire to understand complex systems and theories. They are independent thinkers, problem-solvers, and excel in roles that involve analysis and conceptual thinking. Ravens value intellectual challenges, learning, and autonomy. They dislike rigid structures, ignorance, and being micromanaged.",
    bestMatch: ["ENFJ", "ENFP", "ENTP"],
    worstMatch: ["ESFP", "ESTP", "ISFP"],
    thingsTheyLike: "Intellectual challenges, learning, autonomy",
    thingsTheyHate: "Rigid structures, ignorance, being micromanaged",
  },
  {
    name: "Turtle",
    type: "INFP",
    image: "/images/turtle.png",
    description: "Turtles are introspective and empathetic individuals with a strong desire to make the world a better place. They are creative, patient, and excel in roles that involve personal growth and helping others. Turtles value creativity, personal values, and making a difference. They dislike conflict, criticism, and feeling unappreciated.",
    bestMatch: ["ESTJ", "ESFJ", "ENFJ"],
    worstMatch: ["ISTJ", "ISTP", "ESTJ"],
    thingsTheyLike: "Creativity, personal values, making a difference",
    thingsTheyHate: "Conflict, criticism, feeling unappreciated",
  },
];

export default animals;
